const CANVAS_WIDTH = 800;
const CANVAS_HEIGHT = 800;

const GAME_WIDTH = 300;
const GAME_HEIGHT = 600;

const GAME_WIDTH_GRID = 5;
const GAME_HEIGHT_GRID = 10;

const GUTTER = 1;

const FPS = 60;
const GAME_SPEED = 100;

const PUZZLE_WIDTH = GAME_WIDTH / GAME_WIDTH_GRID
const PUZZLE_HEIGHT = GAME_HEIGHT / GAME_HEIGHT_GRID

const IMAGE_SOURCE = './assets/image.png'

const GAME_START = 'BAT_DAU'
const GAME_OVER = 'GAME_OVER'
const WIN = 'WIN'

const RESTART = 'CHOI_LAI'
const RESET = 'RESET'
const PAUSE = 'PAUSE'